version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: klog-db
    restart: always
    ports:
      - "5444:5432"
    env_file:
      - .env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
